### ISSUE TITLE
code

### ISSUE THREAD

**Issue by 152haha** [mylonasc/gnn-tcnn#1]
Hello, could you please provide the code of this paper

**Comment by 152haha** [comment]
thanks

**Comment by mylonasc** [comment]
Hey @152haha, the gnn library used for this is an earlier version of [tf_gnns](https://github.com/mylonasc/tf_gnns). I didn't find the time yet to implement it with the more efficient and clean version of tf_gnns but since there is interest I will see to it by the end of March.

**Comment by fengxy369** [comment]
Hello, would you still provide the code of this paper in the future？

**Comment by mylonasc** [comment]
Hello @fengxy369 - you can find my latest version from my private repository that I just made public that contains an assortment of experiments and notebooks related to this here: https://github.com/mylonasc/deep-rul-models 

I mention in the README comments some notebooks you may want to check out.

Please feel free to email me for further questions. I'm closing this issue.
